In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2,7,8,9,3, 4, 5])

In [3]:
np.sort(arr)

array([1, 2, 3, 4, 5, 7, 8, 9])

In [8]:
np.searchsorted(arr,10)

8

In [9]:
np.count_nonzero(arr)

8

In [11]:
np.where(arr>5)

(array([2, 3, 4], dtype=int64),)

In [12]:
np.extract(arr==5,arr)

array([5])

Bytes of data

In [14]:
arr.byteswap()

array([ 16777216,  33554432, 117440512, 134217728, 150994944,  50331648,
        67108864,  83886080])

Copies and Views

In [15]:
a=np.copy(arr)  # its deep copy

In [16]:
b= arr.view() # its shallow copy

In [19]:
b[0]=10

In [20]:
arr

array([10,  2,  7,  8,  9,  3,  4,  5])

In [28]:
import numpy.matlib as nm 

In [29]:
nm.eye(3)

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [22]:
nm.zeros((3,3))

matrix([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [30]:
nm.ones((3,3))

matrix([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [31]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [33]:
arr1 = np.array([[2,2,3],[3,5,6],[2,8,9]])

In [34]:
np.dot(arr1,arr2)

array([[ 31,  38,  45],
       [ 65,  79,  93],
       [ 97, 116, 135]])

In [35]:
arr1@arr2  # matrix multiplication

array([[ 31,  38,  45],
       [ 65,  79,  93],
       [ 97, 116, 135]])

In [36]:
vector = np.array(arr)


In [39]:
import nltk
from nltk.chat.util import Chat, reflections

# Pairs is a list of patterns and responses.
pairs = [
    [
        r"my name is (.*)",
        ["Hello %1, How are you today ?",],
    ],
    [
        r"hi|hey|hello",
        ["Hello", "Hey there",],
    ],
    [
        r"quit",
        ["Bye. It was nice talking to you. See you soon :)"],
    ],
]

def chatbot():
    """Function to start and handle the chat."""
    print("Hi, I'm the chatbot you built. You can start a conversation with me now.")
    
    chat = Chat(pairs, reflections)
    chat.converse()

# Call the chatbot function to begin a conversation.
chatbot()

Hi, I'm the chatbot you built. You can start a conversation with me now.
Hello saksham, How are you today ?
None
Hey there
Bye. It was nice talking to you. See you soon :)
