In [1]:
import numpy as np

In [2]:
l=[1,2,34,5,56,6]

In [3]:
ar=np.array(l)

In [4]:
ar

array([ 1,  2, 34,  5, 56,  6])

In [6]:
type(ar)  # n dimentional array

numpy.ndarray

for making array in python 

In [26]:
a=np.array([[1,2],[3,4]])

In [25]:
np.asarray(l)

array([ 1,  2, 34,  5, 56,  6])

In [10]:
np.asanyarray(l)

array([ 1,  2, 34,  5, 56,  6])

matrix in numpy
it has By-default 2d
in np arr --> swallow copy=(same array can be defined by different variable) to make copy use copy

In [14]:
#by default 2d

np.matrix(l)

matrix([[ 1,  2, 34,  5, 56,  6]])

In [28]:
b=a

In [29]:
a[0]=4

making copy of b

In [32]:
c=np.copy(b)

In [33]:
c

array([[4, 4],
       [3, 4]])

In [2]:
import numpy as np


In [3]:
np.fromfunction(lambda i,j : i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [4]:
np.fromfunction(lambda i,j : i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [5]:
iterr=(i*i for i in range(5))

In [7]:
np.fromiter(iterr,float)

array([ 0.,  1.,  4.,  9., 16.])

In [8]:
np.fromstring('1,3,4,5',sep=',')

array([1., 3., 4., 5.])

In [11]:
l=[1., 3., 4., 5.]
ar=np.array(l)

In [13]:
ar.size

4

In [14]:
ar.shape

(4,)

In [15]:
ar.ndim

1

In [19]:
arr=np.array([[1,2],[3,4]])

In [24]:
arr.ndim

2

In [25]:
arr.dtype

dtype('int32')

#### range() in np is arange() for float value (start,end,jump)

In [27]:
np.arange(1,5,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

matrix([[2., 3., 4., 5., 6., 7., 8., 9.]])

In [30]:
np.linspace(1,5,6)

array([1. , 1.8, 2.6, 3.4, 4.2, 5. ])

In [33]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [34]:
np.zeros((2,3,2)) # (z,y,x)-->number of values = dimension

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [37]:
a=np.ones((2,2))

In [38]:
a*4

array([[4., 4.],
       [4., 4.]])

In [42]:
np.empty((3,4)) # --> had value but it is negligible

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [43]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [44]:
np.logspace(4,4,10) #--> (R,C,no.of data)it will give the log value for range with default base 10

array([10000., 10000., 10000., 10000., 10000., 10000., 10000., 10000.,
       10000., 10000.])

In [46]:
a1=np.random.randn(3,3)  # --> std normal distribution std=1 mean=0

In [47]:
import pandas as pd
pd.DataFrame(a1)

0         1         2
0  1.061852  0.898302  1.097241
1  0.426037 -0.067783 -1.420821
2  2.716356  1.080588 -1.723050

In [48]:
np.random.rand(3,3)

array([[0.61230432, 0.98674729, 0.4960224 ],
       [0.93050323, 0.69199482, 0.11262407],
       [0.85633709, 0.73390747, 0.37786128]])

In [51]:
np.random.randint(1,5,(2,2))

array([[1, 3],
       [1, 1]])

In [56]:
a1.reshape(3,-1)  #--> -1 is understad your_self

array([[ 1.06185246,  0.89830231,  1.09724097],
       [ 0.4260368 , -0.06778267, -1.42082088],
       [ 2.71635623,  1.08058799, -1.72305011]])

data sliceing 

In [58]:
a1[0][1]

0.8983023066847141

In [60]:
a1[:2,:2]

array([[ 1.06185246,  0.89830231],
       [ 0.4260368 , -0.06778267]])

In [75]:
axx=np.random.randint(1,10,(5,5))
ax

array([[8, 9, 2, 4, 2],
       [2, 1, 9, 2, 3],
       [2, 3, 2, 3, 1],
       [8, 2, 1, 4, 3],
       [5, 8, 9, 4, 5]])

In [70]:
ax[ax<5]

array([2, 4, 2, 2, 1, 2, 3, 2, 3, 2, 3, 1, 2, 1, 4, 3, 4])

In [71]:
ax<5

array([[False, False,  True,  True,  True],
       [ True,  True, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [False,  True,  True,  True,  True],
       [False, False, False,  True, False]])

In [74]:
ax[2:4,1:3]

array([[3, 2],
       [2, 1]])

In [77]:
ax+axx   #--> matrix addition

array([[10, 17, 10,  6,  6],
       [11,  8, 13, 11,  7],
       [ 9, 12,  7, 11,  7],
       [14,  9,  5, 13,  7],
       [13, 17, 10,  6,  7]])

In [79]:
axx-ax

array([[-6, -1,  6, -2,  2],
       [ 7,  6, -5,  7,  1],
       [ 5,  6,  3,  5,  5],
       [-2,  5,  3,  5,  1],
       [ 3,  1, -8, -2, -3]])

matrix multiplication

In [81]:
ax

array([[8, 9, 2, 4, 2],
       [2, 1, 9, 2, 3],
       [2, 3, 2, 3, 1],
       [8, 2, 1, 4, 3],
       [5, 8, 9, 4, 5]])

In [82]:
axx

array([[2, 8, 8, 2, 4],
       [9, 7, 4, 9, 4],
       [7, 9, 5, 8, 6],
       [6, 7, 4, 9, 4],
       [8, 9, 1, 2, 2]])

In [80]:
ax@axx

array([[151, 191, 128, 153, 100],
       [112, 145,  76, 109,  80],
       [ 71,  85,  51,  76,  46],
       [ 89, 142,  96,  84,  68],
       [209, 250, 138, 200, 132]])

In [83]:
ax/0

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_14408\4258870460.py:1: RuntimeWarning: divide by zero encountered in divide
  ax/0


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [85]:
ax+100

array([[108, 109, 102, 104, 102],
       [102, 101, 109, 102, 103],
       [102, 103, 102, 103, 101],
       [108, 102, 101, 104, 103],
       [105, 108, 109, 104, 105]])

Broadcasting 

In [90]:
ax=np.zeros((3,3))
axx=np.random.randint(1,3,(1,3))
axx

array([[2, 1, 1]])

In [91]:
ax

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [93]:
ax+axx  #broadcasting

array([[2., 1., 1.],
       [2., 1., 1.],
       [2., 1., 1.]])

In [94]:
axx.T

array([[2],
       [1],
       [1]])

In [103]:
np.square(axx)

array([[4, 1, 1]])

In [102]:
np.sqrt(axx)

array([[1.41421356, 1.        , 1.        ]])

In [101]:
np.exp(axx)

array([[7.3890561 , 2.71828183, 2.71828183]])

In [104]:
np.log(axx)

array([[0.69314718, 0.        , 0.        ]])

In [106]:
# Numpy array Manupulating
arr

array([[1, 2],
       [3, 4]])

In [110]:
x=arr.flatten()
x

array([1, 2, 3, 4])

In [111]:
np.expand_dims(x,axis=1)

array([[1],
       [2],
       [3],
       [4]])

In [114]:
d=np.squeeze(axx)
d                   #---> dicrease dim 

array([2, 1, 1])

In [117]:
arr

array([[1, 2],
       [3, 4]])

In [116]:
np.repeat(arr,2)

array([1, 1, 2, 2, 3, 3, 4, 4])

rolls value by 3 posission

In [125]:
x

array([1, 2, 3, 4])

In [124]:
np.roll(x,2)

array([3, 4, 1, 2])

In [126]:
arr

array([[1, 2],
       [3, 4]])

In [123]:
np.roll(arr,2)  

array([[3, 4],
       [1, 2]])

for making diag

In [127]:
np.diag(x)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

binnary operators

In [130]:
arx=np.random.randint(1,5,(3,3))

In [131]:
arxx=np.random.randint(1,5,(3,3))

In [132]:
arx

array([[2, 4, 4],
       [2, 1, 2],
       [2, 1, 1]])

In [133]:
arxx

array([[4, 1, 2],
       [4, 4, 4],
       [4, 3, 4]])

Divison

In [134]:
arxx%arx

array([[0, 1, 2],
       [0, 0, 0],
       [0, 0, 0]])

In [135]:
arx ** arxx

array([[16,  4, 16],
       [16,  1, 16],
       [16,  1,  1]])

 Binary oprations AND operations OR ,Negation

In [136]:
~arx

array([[-3, -5, -5],
       [-3, -2, -3],
       [-3, -2, -2]])

In [137]:
arx & arxx

array([[0, 0, 0],
       [0, 0, 0],
       [0, 1, 0]])

In [138]:
arx

array([[2, 4, 4],
       [2, 1, 2],
       [2, 1, 1]])

In [139]:
arxx

array([[4, 1, 2],
       [4, 4, 4],
       [4, 3, 4]])

In [140]:
arx | arxx

array([[6, 5, 6],
       [6, 5, 6],
       [6, 3, 5]])

In [142]:
arx<arxx

array([[ True, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [145]:
ad=np.array(["True","True","False","False"])


In [147]:
np.char.upper(ad)

array(['TRUE', 'TRUE', 'FALSE', 'FALSE'], dtype='<U5')

In [148]:
np.char.lower(ad)

array(['true', 'true', 'false', 'false'], dtype='<U5')

In [149]:
np.char.capitalize(ad)

array(['True', 'True', 'False', 'False'], dtype='<U5')

In [150]:
np.sin(arx)

array([[ 0.90929743, -0.7568025 , -0.7568025 ],
       [ 0.90929743,  0.84147098,  0.90929743],
       [ 0.90929743,  0.84147098,  0.84147098]])

In [151]:
np.tan(arx)

array([[-2.18503986,  1.15782128,  1.15782128],
       [-2.18503986,  1.55740772, -2.18503986],
       [-2.18503986,  1.55740772,  1.55740772]])

In [153]:
np.tanh(arx)   # it might be hiper tangent

array([[0.96402758, 0.9993293 , 0.9993293 ],
       [0.96402758, 0.76159416, 0.96402758],
       [0.96402758, 0.76159416, 0.76159416]])

In [154]:
np.log10(arx)

array([[0.30103   , 0.60205999, 0.60205999],
       [0.30103   , 0.        , 0.30103   ],
       [0.30103   , 0.        , 0.        ]])

In [155]:
np.power(arx,2)

array([[ 4, 16, 16],
       [ 4,  1,  4],
       [ 4,  1,  1]], dtype=int32)

In [156]:
np.mean(arx)

2.111111111111111

In [157]:
np.std(arx)

1.0999438818457405

In [158]:
np.cov(arx)

array([[ 1.33333333, -0.33333333, -0.66666667],
       [-0.33333333,  0.33333333,  0.16666667],
       [-0.66666667,  0.16666667,  0.33333333]])

In [159]:
np.max(arx)

4